services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./app/ddl:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./app/dbt_integrado2:/app/dbt_integrado2
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    environment:
      DBT_PROFILES_DIR: /app/dbt_integrado2
    command: >
      bash -c "
      dbt debug &&
      dbt run &&
      streamlit run main.py"

volumes:
  pgdata: