
### integrador2/docker-compose.yml

version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  app:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DBT_PROFILES_DIR: /app/dbt_integrado2
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: >
      sh -c "pip install -r requirements.txt &&
             dbt run &&
             streamlit run app/main.py"
    depends_on:
      - postgres

volumes:
  pgdata: